#!/usr/bin/env python3
from __future__ import annotations
import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EMBEDDED = ROOT / "src" / "schads_audit" / "_embedded_rules.py"
DEFAULT_DIST = ROOT / "fabric" / "dist"


def build_rule_module():
    """Embed the canonical effective-dated SCHADS JSON files in the wheel."""
    rules_root = ROOT / "rules" / "MA000100"
    files = {}
    for p in sorted(rules_root.rglob("*.json")):
        files[str(p.relative_to(rules_root)).replace("\\", "/")] = p.read_text(
            encoding="utf-8"
        )
    if not files:
        raise RuntimeError(f"No SCHADS rule JSON files found under {rules_root}")
    source = (
        '"""Generated by fabric/scripts/build_fabric_wheel.py. Do not edit."""\n'
        + "RULE_FILES = "
        + repr(files)
        + "\n"
    )
    EMBEDDED.write_text(source, encoding="utf-8")
    return len(files)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--output-dir",
        default=str(DEFAULT_DIST),
        help="Directory in which the Fabric wheel will be written.",
    )
    args = ap.parse_args()
    dist = Path(args.output_dir).resolve()

    count = build_rule_module()
    dist.mkdir(parents=True, exist_ok=True)
    for old in dist.glob("audithero_schads-*.whl"):
        old.unlink()
    try:
        subprocess.run(
            [sys.executable, "-m", "build", "--wheel", "--outdir", str(dist)],
            cwd=ROOT,
            check=True,
        )
    finally:
        # The generated module is a build artifact. Git remains the source of truth.
        EMBEDDED.unlink(missing_ok=True)

    wheels = sorted(dist.glob("audithero_schads-*.whl"))
    if len(wheels) != 1:
        raise RuntimeError(f"Expected one AuditHero wheel in {dist}; found {len(wheels)}")
    print(f"Built {wheels[0]}")
    print(f"Embedded {count} authoritative rule JSON files")


if __name__ == "__main__":
    main()
