#!/usr/bin/env python3
from __future__ import annotations
import argparse
import ast
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EMBEDDED = ROOT / "src" / "schads_audit" / "_embedded_rules.py"
DEFAULT_DIST = ROOT / "fabric" / "dist"


def build_rule_module():
    """Embed the canonical effective-dated SCHADS JSON files in the wheel."""
    rules_root = ROOT / "rules" / "MA000100"
    files = {}
    for p in sorted(rules_root.rglob("*.json")):
        files[str(p.relative_to(rules_root)).replace("\\", "/")] = p.read_text(
            encoding="utf-8"
        )
    if not files:
        raise RuntimeError(f"No SCHADS rule JSON files found under {rules_root}")
    if "manifest.json" not in files:
        raise RuntimeError("SCHADS rule library has no manifest.json to embed")
    source = (
        '"""Generated by fabric/scripts/build_fabric_wheel.py. Do not edit."""\n'
        + "RULE_FILES = "
        + repr(files)
        + "\n"
    )
    EMBEDDED.write_text(source, encoding="utf-8")
    return files


def verify_wheel(wheel: Path, expected_files: dict[str, str]):
    """Verify the finished wheel physically contains the generated rule payload."""
    with zipfile.ZipFile(wheel, "r") as zf:
        names=set(zf.namelist())
        embedded=[n for n in names if n.endswith("schads_audit/_embedded_rules.py")]
        if len(embedded) != 1:
            raise RuntimeError(
                f"Fabric wheel must contain exactly one schads_audit/_embedded_rules.py; found {embedded}"
            )
        source=zf.read(embedded[0]).decode("utf-8")

    tree=ast.parse(source)
    payload=None
    for node in tree.body:
        if isinstance(node,ast.Assign) and any(isinstance(t,ast.Name) and t.id=="RULE_FILES" for t in node.targets):
            payload=ast.literal_eval(node.value); break
    if not isinstance(payload,dict):
        raise RuntimeError("Could not resolve RULE_FILES from embedded wheel payload")
    if set(payload) != set(expected_files):
        missing=sorted(set(expected_files)-set(payload)); extra=sorted(set(payload)-set(expected_files))
        raise RuntimeError(f"Fabric wheel rule payload mismatch; missing={missing}, extra={extra}")
    if payload.get("manifest.json") != expected_files.get("manifest.json"):
        raise RuntimeError("Embedded SCHADS manifest does not match canonical source")
    print(f"Verified embedded rule payload in {wheel.name}: {len(payload)} JSON files")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--output-dir",
        default=str(DEFAULT_DIST),
        help="Directory in which the Fabric wheel will be written.",
    )
    args = ap.parse_args()
    dist = Path(args.output_dir).resolve()

    files = build_rule_module()
    dist.mkdir(parents=True, exist_ok=True)
    for old in dist.glob("audithero_schads-*.whl"):
        old.unlink()
    try:
        subprocess.run(
            [sys.executable, "-m", "build", "--wheel", "--outdir", str(dist)],
            cwd=ROOT,
            check=True,
        )
    finally:
        # The generated module is a build artifact. Git remains the source of truth.
        EMBEDDED.unlink(missing_ok=True)

    wheels = sorted(dist.glob("audithero_schads-*.whl"))
    if len(wheels) != 1:
        raise RuntimeError(f"Expected one AuditHero wheel in {dist}; found {len(wheels)}")
    verify_wheel(wheels[0],files)
    print(f"Built {wheels[0]}")
    print(f"Embedded {len(files)} authoritative rule JSON files")


if __name__ == "__main__":
    main()
