#!/usr/bin/env python3
from __future__ import annotations
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EMBEDDED = ROOT / "src" / "schads_audit" / "_embedded_rules.py"
DIST = ROOT / "fabric" / "dist"


def build_rule_module():
    rules_root = ROOT / "rules" / "MA000100"
    files = {}
    for p in sorted(rules_root.rglob("*.json")):
        files[str(p.relative_to(rules_root)).replace("\\", "/")] = p.read_text(
            encoding="utf-8"
        )
    source = (
        '"""Generated by fabric/scripts/build_fabric_wheel.py. Do not edit."""\n'
        + "RULE_FILES = "
        + repr(files)
        + "\n"
    )
    EMBEDDED.write_text(source, encoding="utf-8")
    return len(files)


def main():
    count = build_rule_module()
    DIST.mkdir(parents=True, exist_ok=True)
    for old in DIST.glob("audithero_schads-*.whl"):
        old.unlink()
    try:
        subprocess.run(
            [sys.executable, "-m", "build", "--wheel", "--outdir", str(DIST)],
            cwd=ROOT,
            check=True,
        )
    finally:
        EMBEDDED.unlink(missing_ok=True)
    wheels = sorted(DIST.glob("audithero_schads-*.whl"))
    if len(wheels) != 1:
        raise RuntimeError(f"Expected one AuditHero wheel; found {len(wheels)}")
    print(f"Built {wheels[0]}")
    print(f"Embedded {count} authoritative rule JSON files")


if __name__ == "__main__":
    main()
