command:
  - streamlit
  - run
  - app.py
  - --server.address=0.0.0.0
  - --server.port=8000
env:
  - name: WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: AUDITHERO_CATALOG
    value: schads_payroll
